DROP TABLE IF EXISTS public.USERS CASCADE;
DROP TABLE IF EXISTS public.AUTHORS CASCADE;
DROP TABLE IF EXISTS public.GENRES CASCADE;
DROP TABLE IF EXISTS public.BOOKS CASCADE;
DROP TABLE IF EXISTS public.NOTES CASCADE;

CREATE TABLE IF NOT EXISTS public.USERS(ID BIGINT PRIMARY KEY, USERNAME VARCHAR(500) not null unique, PASSWORD VARCHAR(500) not null, AUTHORITY VARCHAR(500) not null);

CREATE TABLE IF NOT EXISTS public.AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(500) not null);

CREATE TABLE IF NOT EXISTS public.GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(500) not null unique);

CREATE TABLE IF NOT EXISTS public.BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(500) not null, AUTHOR_ID BIGINT not null, GENRE_ID BIGINT not null);

ALTER TABLE IF EXISTS public.BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES public.AUTHORS(ID);
ALTER TABLE IF EXISTS public.BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES public.GENRES(ID);

CREATE TABLE IF NOT EXISTS public.NOTES(ID BIGINT PRIMARY KEY, NOTE_TEXT VARCHAR(1000) not null, NOTE_DATE TIMESTAMP not null, NOTE_AUTHOR VARCHAR(250), BOOK_ID BIGINT);

ALTER TABLE IF EXISTS public.NOTES ADD FOREIGN KEY (BOOK_ID) REFERENCES public.BOOKS(ID);

