DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null unique);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null, AUTHOR_ID LONG, GENRE_ID LONG);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID);
