spring:
  datasource:
    url: jdbc:h2:mem:lib
    username: denis
    password: denis
    driver-class-name: org.h2.Driver

    schema:
      classpath: schema.sql
    data:
      classpath: data.sql

  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true