spring:
  data:
    mongodb:
      port: 0
      database: lib

mongock:
  runner-type: "ApplicationRunner" # default
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog

  mongo-db:
    write-concern:
      journal: false
    read-concern: local