DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null unique);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null, AUTHOR_ID LONG not null, GENRE_ID LONG not null);

ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);
ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID);

DROP TABLE IF EXISTS NOTES;
CREATE TABLE NOTES(ID LONG PRIMARY KEY AUTO_INCREMENT, NOTE_TEXT VARCHAR(1000) not null, NOTE_DATE TIMESTAMP not null, NOTE_AUTHOR VARCHAR(250), BOOK_ID LONG);

ALTER TABLE NOTES ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID);
