CREATE TABLE IF NOT EXISTS USERS(ID LONG PRIMARY KEY AUTO_INCREMENT, USERNAME VARCHAR(500) not null unique, PASSWORD VARCHAR(500) not null);

CREATE TABLE IF NOT EXISTS AUTHORS(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null);

CREATE TABLE IF NOT EXISTS GENRES(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null unique);

CREATE TABLE IF NOT EXISTS BOOKS(ID LONG PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(500) not null, AUTHOR_ID LONG not null, GENRE_ID LONG not null);

ALTER TABLE IF EXISTS BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);
ALTER TABLE IF EXISTS BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID);

CREATE TABLE IF NOT EXISTS NOTES(ID LONG PRIMARY KEY AUTO_INCREMENT, NOTE_TEXT VARCHAR(1000) not null, NOTE_DATE TIMESTAMP not null, NOTE_AUTHOR VARCHAR(250), BOOK_ID LONG);

ALTER TABLE IF EXISTS NOTES ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID);

